name: new_rlyuo_image_move
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: new_rlyuo_image_move
      uses: Yikun/hub-mirror-action@master 
      with:
        src: github/rlyuo
        dst: gitee/ryuo
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} 
        dst_token:  ${{ secrets.GITEE_TOKEN }} 
        account_type: user
        clone_style: "ssh" 
        debug: true 
        force_update: true 
        white_list: "llvm-project" 
        timeout: '6000s' 
